# Generated by Django 5.2.4 on 2026-06-23 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('detail', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PreacherMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(default='Preachers Desk', max_length=120)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('image_path', models.CharField(default='church/images/worshippers.jfif', max_length=255)),
                ('button_text', models.CharField(default='More', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Service', max_length=120)),
                ('description', models.TextField()),
                ('image_path', models.CharField(default='church/images/worshippers.jfif', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(default="St. Bartholomew's", max_length=120)),
                ('church_subtitle', models.CharField(default='Anglican Church Enugu.', max_length=120)),
                ('logo_path', models.CharField(default='church/images/images.png', max_length=255)),
                ('welcome_heading', models.CharField(default='Welcome to the Fountain of Purity', max_length=160)),
                ('welcome_text', models.TextField()),
                ('footer_tagline', models.CharField(default='Raising a worshipping, word-grounded, and Christ-centered community.', max_length=180)),
                ('contact_email', models.EmailField(default='info@gracechurch.org', max_length=254)),
                ('address', models.CharField(default='Enugu, Nigeria', max_length=180)),
            ],
            options={
                'verbose_name': 'Site profile',
                'verbose_name_plural': 'Site profile',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image_path', models.CharField(help_text='Use a static path like church/images/name.png or a full https:// URL.', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('activity', models.CharField(max_length=120)),
                ('time', models.CharField(max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Weekly activities',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='church.service')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
