# Generated by Django 5.2.4 on 2026-06-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_seed_homepage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='video_path',
            field=models.CharField(blank=True, help_text='Optional. Use a static path like church/videos/intro.mp4 or a full https:// URL. If set, the video is shown instead of the image.', max_length=500),
        ),
    ]
