# Generated by Django 5.2.4 on 2026-06-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_slide_video_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image_path',
            field=models.FileField(help_text='Upload an image for this slide. Used when no video is uploaded.', max_length=500, upload_to='slides/images/'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='video_path',
            field=models.FileField(blank=True, help_text='Optional. Upload a short video. If set, the video is shown instead of the image.', max_length=500, upload_to='slides/videos/'),
        ),
    ]
