# Generated by Django 5.2.4 on 2026-06-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_alter_slide_image_path_alter_slide_video_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClergyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('position', models.CharField(max_length=120)),
                ('image', models.FileField(max_length=500, upload_to='clergy/images/')),
                ('is_lead_pastor', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_lead_pastor', 'order', 'id'],
            },
        ),
    ]
