# Generated by Django 5.2.4 on 2026-06-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_clergyprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetime',
            name='service',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceTime',
        ),
    ]
