# Generated by Django 5.2.4 on 2026-07-03 11:11

import django.db.models.deletion
from django.db import migrations, models


def seed_faith_cards(apps, schema_editor):
    FaithCardGrid = apps.get_model("church", "FaithCardGrid")
    FaithCardDetail = apps.get_model("church", "FaithCardDetail")

    cards = [
        (
            "Sundays Worship",
            "Sunday praise, prayer, Word, Sacrament, thanksgiving, and devotion.",
            "Sunday Worship",
            "Sunday praise and prayer\nWord and Sacrament\nThanksgiving and devotion",
        ),
        (
            "Mid-Week Services",
            "Care groups, ministries, youth support, family support, service, and friendship.",
            "Mid-Week Services",
            "Care groups and ministries\nYouth and family support\nShared service and friendship",
        ),
        (
            "Monthly Vigils",
            "Evangelism, discipleship, community care, and daily Christian witness.",
            "Carry The Gospel Outward",
            "Evangelism and discipleship\nCompassionate community care\nWitness through daily living",
        ),
    ]

    for order, (title, content, detail_title, detail_content) in enumerate(cards):
        card, _ = FaithCardGrid.objects.get_or_create(
            title=title,
            defaults={
                "content": content,
                "order": order,
                "is_active": True,
            },
        )
        FaithCardDetail.objects.get_or_create(
            grid=card,
            title=detail_title,
            defaults={
                "content": detail_content,
                "order": 0,
                "is_active": True,
            },
        )


def unseed_faith_cards(apps, schema_editor):
    FaithCardGrid = apps.get_model("church", "FaithCardGrid")
    FaithCardGrid.objects.filter(
        title__in=["Sundays Worship", "Mid-Week Services", "Monthly Vigils"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_remove_servicetime_service_delete_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaithCardGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Faith card',
                'verbose_name_plural': 'Faith cards',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FaithCardDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField(help_text='Enter each bullet point on a new line.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='church.faithcardgrid')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(seed_faith_cards, unseed_faith_cards),
    ]
