# Generated by Django 5.2.4 on 2026-07-03 11:39

from django.db import migrations, models


def keep_one_detail_per_faith_card(apps, schema_editor):
    FaithCardDetail = apps.get_model("church", "FaithCardDetail")

    grid_ids = (
        FaithCardDetail.objects.values_list("grid_id", flat=True)
        .distinct()
        .order_by("grid_id")
    )

    for grid_id in grid_ids:
        detail_ids = list(
            FaithCardDetail.objects.filter(grid_id=grid_id)
            .order_by("order", "id")
            .values_list("id", flat=True)
        )
        FaithCardDetail.objects.filter(id__in=detail_ids[1:]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0007_faithcardgrid_faithcarddetail'),
    ]

    operations = [
        migrations.RunPython(keep_one_detail_per_faith_card, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='faithcarddetail',
            constraint=models.UniqueConstraint(fields=('grid',), name='unique_faith_card_detail_per_grid'),
        ),
    ]
