# Generated by Django 5.2.4 on 2026-07-03 12:37

from datetime import date

import django.db.models.deletion
from django.db import migrations, models


def seed_departments(apps, schema_editor):
    Department = apps.get_model("church", "Department")
    DepartmentActivityArticle = apps.get_model("church", "DepartmentActivityArticle")
    DepartmentActivityPhoto = apps.get_model("church", "DepartmentActivityPhoto")
    DepartmentEvent = apps.get_model("church", "DepartmentEvent")

    departments = [
        ("Men's Fellowship", "mens-fellowship", "Building faithful men for worship, service, and leadership."),
        ("Women's Fellowship", "womens-fellowship", "Nurturing women in prayer, fellowship, service, and discipleship."),
        ("Anglican Youth Fellowship", "anglican-youth-fellowship", "Raising young people who love Christ and serve with purpose."),
        ("The Choir", "the-choir", "Leading the church in reverent, joyful, and excellent worship."),
        ("EFAC Fellowship", "efac-fellowship", "Encouraging evangelical faith, Bible study, and mission."),
        ("Anglican Children Ministry", "anglican-children-ministry", "Helping children grow in faith, worship, and character."),
        ("The Girls Guild", "the-girls-guild", "Training girls in Christian discipline, service, and confidence."),
        ("The Ushering Team", "the-ushering-team", "Serving the congregation with order, warmth, and hospitality."),
    ]
    scroller_images = [
        ("church/images/worshippers.jfif", "Department worship and fellowship"),
        ("church/images/worshippers2.jfif", "Ministry activity"),
        ("church/images/worshippers3.jfif", "Community service"),
    ]

    for order, (name, slug, tagline) in enumerate(departments):
        department, _ = Department.objects.get_or_create(
            slug=slug,
            defaults={
                "name": name,
                "tagline": tagline,
                "hero_image": "church/images/St.-Barts-Asata-Enugu.png",
                "introduction": (
                    f"{name} is a ministry of St. Bartholomew's Anglican Church dedicated to "
                    "spiritual growth, fellowship, service, and active participation in the life "
                    "of the church. Members gather to encourage one another, support church "
                    "programs, and serve the wider community with Christ-centered purpose."
                ),
                "leader_name": "",
                "leader_title": "Department Leader",
                "leader_image": "church/images/worshippers.jfif",
                "executives_title": "Department Executives",
                "executives_image": "church/images/worshippers2.jfif",
                "order": order,
                "is_active": True,
            },
        )

        DepartmentActivityArticle.objects.get_or_create(
            department=department,
            title="Regular Fellowship And Activities",
            defaults={
                "frequency": "Weekly / Monthly",
                "body": (
                    "The department holds regular meetings, prayer moments, rehearsals, "
                    "training sessions, outreach activities, and fellowship programs according "
                    "to its ministry calendar."
                ),
                "order": 0,
                "is_active": True,
            },
        )

        for photo_order, (image, caption) in enumerate(scroller_images):
            DepartmentActivityPhoto.objects.get_or_create(
                department=department,
                image=image,
                defaults={
                    "caption": caption,
                    "order": photo_order,
                    "is_active": True,
                },
            )

        DepartmentEvent.objects.get_or_create(
            department=department,
            title="Department Fellowship",
            defaults={
                "date": date(2026, 8, 16),
                "time": "After service",
                "venue": "Church premises",
                "description": "Details will be confirmed by the department executives.",
                "order": 0,
                "is_active": True,
            },
        )


def unseed_departments(apps, schema_editor):
    Department = apps.get_model("church", "Department")
    Department.objects.filter(
        slug__in=[
            "mens-fellowship",
            "womens-fellowship",
            "anglican-youth-fellowship",
            "the-choir",
            "efac-fellowship",
            "anglican-children-ministry",
            "the-girls-guild",
            "the-ushering-team",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0008_faithcarddetail_unique_faith_card_detail_per_grid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=180)),
                ('hero_image', models.FileField(blank=True, max_length=500, upload_to='departments/hero/')),
                ('introduction', models.TextField(help_text='A short paragraph explaining who this department is.')),
                ('leader_name', models.CharField(blank=True, max_length=120)),
                ('leader_title', models.CharField(blank=True, default='Department Leader', max_length=120)),
                ('leader_image', models.FileField(blank=True, max_length=500, upload_to='departments/leaders/')),
                ('executives_title', models.CharField(blank=True, default='Executives', max_length=120)),
                ('executives_image', models.FileField(blank=True, max_length=500, upload_to='departments/executives/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentActivityArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('frequency', models.CharField(default='Weekly', max_length=40)),
                ('body', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_articles', to='church.department')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentActivityPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=500, upload_to='departments/activities/')),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_photos', to='church.department')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('date', models.DateField()),
                ('time', models.CharField(blank=True, max_length=40)),
                ('venue', models.CharField(blank=True, max_length=140)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='church.department')),
            ],
            options={
                'ordering': ['date', 'order', 'id'],
            },
        ),
        migrations.RunPython(seed_departments, unseed_departments),
    ]
