# Generated by Django 5.2.4 on 2026-07-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0009_department_departmentactivityarticle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='facebook_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='instagram_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='office_hours',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='whatsapp_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='youtube_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
