# Generated by Django 5.2.4 on 2026-07-04 23:52

from django.db import migrations, models


def seed_church_families(apps, schema_editor):
    ChurchFamily = apps.get_model("church", "ChurchFamily")
    families = [
        {
            "name": "Ifunanya",
            "slug": "ifunanya",
            "meaning": "Love Group",
            "image": "church/images/worshippers.jfif",
            "body": (
                "Ifunanya family welcomes members into a warm circle of care, prayer, "
                "and practical support. The group encourages every household to grow in "
                "love for Christ and in love for one another."
            ),
            "order": 1,
        },
        {
            "name": "Okwukwe",
            "slug": "okwukwe",
            "meaning": "Faith Group",
            "image": "church/images/worshippers2.jfif",
            "body": (
                "Okwukwe family strengthens members through Bible study, fellowship, "
                "and shared encouragement. The group helps families stand firmly in "
                "faith while serving the wider church community."
            ),
            "order": 2,
        },
        {
            "name": "Amara",
            "slug": "amara",
            "meaning": "Grace Group",
            "image": "church/images/worshippers3.jfif",
            "body": (
                "Amara family reflects God's grace through hospitality, visitation, "
                "and consistent care for members. The group creates room for people "
                "to belong, heal, and serve with joy."
            ),
            "order": 3,
        },
        {
            "name": "Udoka",
            "slug": "udoka",
            "meaning": "Peace Group",
            "image": "church/images/St.-Barts-Asata-Enugu.png",
            "body": (
                "Udoka family nurtures unity, peace, and Christian friendship across "
                "generations. Members support one another in worship, service, and the "
                "daily walk of discipleship."
            ),
            "order": 4,
        },
    ]

    for family in families:
        ChurchFamily.objects.get_or_create(slug=family["slug"], defaults=family)


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0010_siteprofile_contact_phone_siteprofile_facebook_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('meaning', models.CharField(help_text='Example: Love Group', max_length=120)),
                ('body', models.TextField()),
                ('image', models.FileField(blank=True, default='church/images/worshippers.jfif', max_length=500, upload_to='families/images/')),
                ('male_leader_name', models.CharField(default='Male Group Leader', max_length=120)),
                ('male_leader_image', models.FileField(blank=True, default='church/images/5883.jpg', max_length=500, upload_to='families/leaders/')),
                ('female_leader_name', models.CharField(default='Female Group Leader', max_length=120)),
                ('female_leader_image', models.FileField(blank=True, default='church/images/13338.jpg', max_length=500, upload_to='families/leaders/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Church families',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RunPython(seed_church_families, migrations.RunPython.noop),
    ]
