# Generated by Django 5.2.4 on 2026-07-05 00:24

import django.db.models.deletion
from django.db import migrations, models


def seed_family_slider_images(apps, schema_editor):
    ChurchFamily = apps.get_model("church", "ChurchFamily")
    ChurchFamilySliderImage = apps.get_model("church", "ChurchFamilySliderImage")

    for family in ChurchFamily.objects.all():
        if not family.image:
            continue

        ChurchFamilySliderImage.objects.get_or_create(
            family=family,
            order=0,
            defaults={"image": family.image},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0011_churchfamily'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchFamilySliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=500, upload_to='families/slider/')),
                ('write_up', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_images', to='church.churchfamily')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(seed_family_slider_images, migrations.RunPython.noop),
    ]
