# Generated by Django 5.2.4 on 2026-07-13 08:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0012_churchfamilysliderimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preachermessage',
            options={'ordering': ['-date_posted', 'order', 'id']},
        ),
        migrations.AddField(
            model_name='preachermessage',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='preachermessage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='preachermessage',
            name='preacher_image',
            field=models.FileField(blank=True, default='church/images/worshippers.jfif', help_text='Small head image shown beside the message.', max_length=500, upload_to='preachers/images/'),
        ),
        migrations.AddField(
            model_name='preachermessage',
            name='preacher_name',
            field=models.CharField(default='Preacher Name', max_length=120),
        ),
        migrations.AddField(
            model_name='preachermessage',
            name='slug',
            field=models.SlugField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='preachermessage',
            name='youtube_url',
            field=models.URLField(blank=True, default='', help_text='Optional YouTube page link for the message video.'),
        ),
    ]
