# Generated by Codex on 2026-07-13

from django.db import migrations, models


def select_existing_homepage_preacher(apps, schema_editor):
    PreacherMessage = apps.get_model("church", "PreacherMessage")
    message = (
        PreacherMessage.objects.filter(is_active=True)
        .order_by("-date_posted", "order", "id")
        .first()
    )

    if message:
        PreacherMessage.objects.filter(pk=message.pk).update(show_on_homepage=True)


class Migration(migrations.Migration):

    dependencies = [
        ("church", "0013_alter_preachermessage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="preachermessage",
            name="show_on_homepage",
            field=models.BooleanField(
                default=False,
                help_text="Show this message in the Preachers Desk section on the home page.",
            ),
        ),
        migrations.RunPython(select_existing_homepage_preacher, migrations.RunPython.noop),
    ]
