# Generated by Codex on 2026-10-08

from django.db import migrations, models


def seed_live_service(apps, schema_editor):
    LiveService = apps.get_model("church", "LiveService")
    LiveService.objects.get_or_create(
        title="Live services on YouTube",
        defaults={
            "video_url": "https://www.youtube.com/shorts/URXsWWWoTfk",
            "order": 0,
            "is_active": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("church", "0014_preachermessage_show_on_homepage"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Live services on YouTube", max_length=120)),
                (
                    "video_url",
                    models.URLField(
                        default="https://www.youtube.com/shorts/URXsWWWoTfk",
                        help_text=(
                            "Paste the live service video link. YouTube watch, shorts, "
                            "live, and embed links are converted automatically."
                        ),
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.RunPython(seed_live_service, migrations.RunPython.noop),
    ]
